export const ADD_PRODUCTS = "ADD_PRODUCTS";

export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";

export const SET_PRODUCTS = "SET_PRODUCTS";

export const SET_SINGLE_PRODUCTS = "SET_SINGLE_PRODUCTS";

export const EDIT_PRODUCTS = "EDIT_PRODUCTS";



